config/routes.rb
Rails.application.routes.draw do
  resources :containers
  resources :stock_items
  resources :device_types
  resources :device_brands
  resources :places
  resources :container_types
  resources :items
  resources :devices
  resources :device_models

  get '/', action: :index, controller: :pages
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  def self.search(query)
    if query.nil? || query.empty?
      return self.all
    end

    case self.verify_type query
    when :integer
      integers_fields = self.fields_by_type ActiveModel::Type::Integer

      where_str = "1=0 "
      integers_fields.each {|field| where_str += " OR #{field} = #{query}"}
      return self.where(where_str)
    when :text
      text_fields = self.fields_by_type ActiveModel::Type::String
      where_str = "1=0 "
      text_fields.each {|field| where_str += " OR #{field} LIKE \"%#{query}%\""}
      return self.where(where_str)
    end

  end

  private
    def self.fields_by_type (type)
      self.attribute_types.select {|attr, attrtype| attrtype.is_a?(type)}.keys;
    end

    def self.verify_type(str)
      return case str
        when /^([0-9]*)?$/ then :integer
        else :text
      end
    end

end

app/models/container.rb
class Container < ApplicationRecord
  belongs_to :place
  belongs_to :item
  belongs_to :container_type
  belongs_to :container
  def to_s
    self.title
  end
end

app/models/container_type.rb
class ContainerType < ApplicationRecord
end

app/models/device.rb
class Device < ApplicationRecord
  belongs_to :item
  belongs_to :device_model
  def to_s
    self.title
  end
end

app/models/device_brand.rb
class DeviceBrand < ApplicationRecord
  def to_s
    self.title
  end
end

app/models/device_model.rb
class DeviceModel < ApplicationRecord
  belongs_to :device_brand
  belongs_to :device_type
end

app/models/device_type.rb
class DeviceType < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord
  def to_s
    self.title
  end
end

app/models/place.rb
class Place < ApplicationRecord
end

app/models/stock_item.rb
class StockItem < ApplicationRecord
  belongs_to :item, required: false
  def to_s
    self.title
  end
end

app/controllers/device_types_controller.rb
class DeviceTypesController < ApplicationController
  before_action :set_device_type, only: [:show, :edit, :update, :destroy]

  # GET /device_types
  def index
    @device_types = DeviceType.all.order(sort_params).page(params[:page])
  end

  # GET /device_types/1
  def show
  end

  # GET /device_types/new
  def new
    @device_type = DeviceType.new
  end

  # GET /device_types/1/edit
  def edit
  end

  # POST /device_types
  def create
    @device_type = DeviceType.new(device_type_params)

    if @device_type.save
      redirect_to device_types_url, :flash => { :success => 'Device type was successfully created.' }
    else
      render :new
    end
  end

  # PATCH/PUT /device_types/1
  def update
    if @device_type.update(device_type_params)
      redirect_to device_types_url, :flash => { :success => 'Device type was successfully updated.' }
    else
      render :edit
    end
  end

  # DELETE /device_types/1
  def destroy
    @device_type.destroy
    redirect_to device_types_url, :flash => { :success => 'Device type was successfully deleted.' }
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_device_type
      @device_type = DeviceType.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def device_type_params
      params.require(:device_type).permit(:title)
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  def index
    @items = Item.all.search(search_params).order(sort_params).page(params[:page])
  end

  # GET /items/1
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  def create
    @item = Item.new(item_params)

    if @item.save
      redirect_to items_url, :flash => { :success => 'Item was successfully created.' }
    else
      render :new
    end
  end

  # PATCH/PUT /items/1
  def update
    if @item.update(item_params)
      redirect_to items_url, :flash => { :success => 'Item was successfully updated.' }
    else
      render :edit
    end
  end

  # DELETE /items/1
  def destroy
    @item.destroy
    redirect_to items_url, :flash => { :success => 'Item was successfully deleted.' }
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def item_params
      params.require(:item).permit(:number, :title, :brand_name, :model_description, :serial_number, :warranty_date, :value, :net_value, :allocation)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index

  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def menu_item(name, icon = nil, options = nil, html_options = nil, &block)
    html_options ||= {}

    html_options[:class] ||= ""
    html_options[:class] += " nav-link"

    if icon.present?
      name = fa_icon icon, :text => name
    end

    active_link_to(name, options, html_options, &block)
  end

  def active_link_to(name = nil, options = nil, html_options = nil, &block)
    html_options ||= {}

    html_options[:class] ||= ""

    html_options[:class] += " active" if current_page?(options)

    link_to(name, options, html_options, &block)
  end

end

app/helpers/containers_helper.rb
module ContainersHelper
end

app/helpers/device_brands_helper.rb
module DeviceBrandsHelper
end

app/helpers/device_models_helper.rb
module DeviceModelsHelper
end

app/helpers/device_types_helper.rb
module DeviceTypesHelper
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/stock_items_helper.rb
module StockItemsHelper
end

app/views/device_types/_form.html.erb
<%= semantic_form_for @device_type do |f| %>
<%= f.inputs do %>
  <%= f.input :title %>
<% end %>

<%= f.actions do %>
<%= f.action :submit, :as => :input %>
<% end %>
<% end %>

app/views/device_types/edit.html.erb
<div class="page-header">
  <h1><%= DeviceType.model_name.human  %></h1>
</div>

<ul class="nav nav-tabs justify-content-end">
  <li class="nav-item">
    <%= link_to (fa_icon 'list', :text => t_title(:index)), device_types_path, :class => 'nav-link' %>
  </li>
  <li class="nav-item">
    <%= link_to (fa_icon 'eye', :text => t_title(:show)), device_type_path(@device_type), :class => 'nav-link ' %>
  </li>
  <li class="nav-item">
    <%= link_to (fa_icon 'edit', :text => t_title(:edit)), edit_device_type_path(@device_type), :class => 'nav-link active ' %>
  </li>
  <li class="nav-item">
    <%= link_to (fa_icon 'trash', :text => t_title(:delete)), device_type_path(@device_type), :class => 'nav-link ', method: :delete, data: { confirm: t_confirm_delete(@device_type) } %>
  </li>
  <li class="nav-item">
    <%= link_to (fa_icon 'plus', :text => t_title(:new)), new_device_type_path, :class => 'nav-link' %>
  </li>
</ul>

<%= render 'form' %>

app/views/device_types/index.html.erb
<div class="page-header">
  <h1><%= DeviceType.model_name.human  %></h1>
</div>

<div class="table-responsive">
  <ul class="nav nav-tabs justify-content-end">
    <li class="nav-item">
      <%= link_to (fa_icon 'list', :text => t_title(:index)), device_types_path, :class => 'nav-link active' %>
    </li>
    <li class="nav-item">
      <%= link_to (fa_icon 'plus', :text => t_title(:new) ), new_device_type_path, :class => 'nav-link' %>
    </li>
  </ul>

  <table class="table table-striped table-hover table-sm">
    <thead>
      <tr>
        <th><%= t_attr(:title) %></th>
        <th class="action"></th>
        <th class="action"></th>
        <th class="action"></th>
      </tr>
    </thead>

    <tbody>
      <% @device_types.each do |device_type| %>
       <tr>
          <td><%= device_type.title %></td>

          <td class="action">
            <%= link_to device_type_path(device_type), :title => t_title(:show), :class => 'btn btn-sm btn-outline-info' do %><i class="far fa-eye"></i><% end %>
          </td>

          <td class="action">
            <%= link_to edit_device_type_path(device_type), :title => t_title(:edit), :class => 'btn btn-sm btn-outline-warning' do %>
              <i class="far fa-edit"></i>
            <% end %>
          </td>

          <td class="action">
            <%= link_to device_type_path(device_type), :title => t_title(:delete),  :class => 'btn btn-sm btn-outline-danger', method: :delete, data: { confirm: t_confirm_delete(device_type) } do %>
              <i class="far fa-trash-alt"></i>
            <% end %>
          </td>
        <% end %>
      </tr>
    </tbody>
  </table>
  <%= paginate(@device_types) %>
</div>

app/views/device_types/new.html.erb
<div class="page-header">
  <h1><%= DeviceType.model_name.human  %></h1>
</div>


<ul class="nav nav-tabs justify-content-end">
  <li class="nav-item">
    <%= link_to (fa_icon 'list', :text => t_title(:index)), device_types_path, :class => 'nav-link' %>
  </li>
  <li class="nav-item">
    <%= link_to (fa_icon 'plus', :text => t_title(:new) ), new_device_type_path, :class => 'nav-link active' %>
  </li>
</ul>

<%= render 'form' %>

app/views/device_types/show.html.erb
<div class="page-header">
  <h1><%= DeviceType.model_name.human  %></h1>
</div>

<div class="table-responsive">
  <ul class="nav nav-tabs justify-content-end">
    <li class="nav-item">
      <%= link_to (fa_icon 'list', :text => t_title(:index)), device_types_path, :class => 'nav-link' %>
    </li>
    <li class="nav-item">
      <%= link_to (fa_icon 'eye', :text => t_title(:show)), device_type_path(@device_type), :class => 'nav-link active' %>
    </li>
    <li class="nav-item">
      <%= link_to (fa_icon 'edit', :text => t_title(:edit)), edit_device_type_path(@device_type), :class => 'nav-link' %>
    </li>
    <li class="nav-item">
      <%= link_to (fa_icon 'trash', :text => t_title(:delete)), device_type_path(@device_type), :class => 'nav-link ', method: :delete, data: { confirm: t_confirm_delete(@device_type) } %>
    </li>
    <li class="nav-item">
      <%= link_to (fa_icon 'plus', :text => t_title(:new)), new_device_type_path, :class => 'nav-link' %>
    </li>
  </ul>
  <table class="table table-striped table-sm">
      <tr>
        <th><%= t_attr(:title) %></th>
        <td><%=  @device_type.title %></td>
      </tr>
  </table>
</div>