config/routes.rb
Rails.application.routes.draw do
  resources :containers
  resources :stock_items
  resources :device_types
  resources :device_brands
  resources :places
  resources :container_types
  resources :items
  resources :devices
  resources :device_models

  get '/', action: :index, controller: :pages
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  def self.search(query)
    if query.nil? || query.empty?
      return self.all
    end

    case self.verify_type query
    when :integer
      integers_fields = self.fields_by_type ActiveModel::Type::Integer

      where_str = "1=0 "
      integers_fields.each {|field| where_str += " OR #{field} = #{query}"}
      return self.where(where_str)
    when :text
      text_fields = self.fields_by_type ActiveModel::Type::String
      where_str = "1=0 "
      text_fields.each {|field| where_str += " OR #{field} LIKE \"%#{query}%\""}
      return self.where(where_str)
    end

  end

  private
    def self.fields_by_type (type)
      self.attribute_types.select {|attr, attrtype| attrtype.is_a?(type)}.keys;
    end

    def self.verify_type(str)
      return case str
        when /^([0-9]*)?$/ then :integer
        else :text
      end
    end

end

app/models/container.rb
class Container < ApplicationRecord
  belongs_to :place
  belongs_to :item
  belongs_to :container_type
  belongs_to :container
  def to_s
    self.title
  end
end

app/models/container_type.rb
class ContainerType < ApplicationRecord
end

app/models/device.rb
class Device < ApplicationRecord
  belongs_to :item
  belongs_to :device_model
  def to_s
    self.title
  end
end

app/models/device_brand.rb
class DeviceBrand < ApplicationRecord
  def to_s
    self.title
  end
end

app/models/device_model.rb
class DeviceModel < ApplicationRecord
  belongs_to :device_brand
  belongs_to :device_type
end

app/models/device_type.rb
class DeviceType < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord
  def to_s
    self.title
  end
end

app/models/place.rb
class Place < ApplicationRecord
end

app/models/stock_item.rb
class StockItem < ApplicationRecord
  belongs_to :item, required: false
  def to_s
    self.title
  end
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  before_action :set_device, only: [:show, :edit, :update, :destroy]

  # GET /devices
  def index
    @devices = Device.all.order(sort_params).page(params[:page])
  end

  # GET /devices/1
  def show
  end

  # GET /devices/new
  def new
    @device = Device.new
  end

  # GET /devices/1/edit
  def edit
  end

  # POST /devices
  def create
    @device = Device.new(device_params)

    if @device.save
      redirect_to devices_url, :flash => { :success => 'Device was successfully created.' }
    else
      render :new
    end
  end

  # PATCH/PUT /devices/1
  def update
    if @device.update(device_params)
      redirect_to devices_url, :flash => { :success => 'Device was successfully updated.' }
    else
      render :edit
    end
  end

  # DELETE /devices/1
  def destroy
    @device.destroy
    redirect_to devices_url, :flash => { :success => 'Device was successfully deleted.' }
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_device
      @device = Device.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def device_params
      params.require(:device).permit(:title, :item_id, :device_model_id, :ip, :host, :description, :unknown)
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  def index
    @items = Item.all.search(search_params).order(sort_params).page(params[:page])
  end

  # GET /items/1
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  def create
    @item = Item.new(item_params)

    if @item.save
      redirect_to items_url, :flash => { :success => 'Item was successfully created.' }
    else
      render :new
    end
  end

  # PATCH/PUT /items/1
  def update
    if @item.update(item_params)
      redirect_to items_url, :flash => { :success => 'Item was successfully updated.' }
    else
      render :edit
    end
  end

  # DELETE /items/1
  def destroy
    @item.destroy
    redirect_to items_url, :flash => { :success => 'Item was successfully deleted.' }
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def item_params
      params.require(:item).permit(:number, :title, :brand_name, :model_description, :serial_number, :warranty_date, :value, :net_value, :allocation)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index

  end

end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :set_place, only: [:show, :edit, :update, :destroy]

  # GET /places
  def index
    @places = Place.all.order(sort_params).page(params[:page])
  end

  # GET /places/1
  def show
  end

  # GET /places/new
  def new
    @place = Place.new
  end

  # GET /places/1/edit
  def edit
  end

  # POST /places
  def create
    @place = Place.new(place_params)

    if @place.save
      redirect_to places_url, :flash => { :success => 'Place was successfully created.' }
    else
      render :new
    end
  end

  # PATCH/PUT /places/1
  def update
    if @place.update(place_params)
      redirect_to places_url, :flash => { :success => 'Place was successfully updated.' }
    else
      render :edit
    end
  end

  # DELETE /places/1
  def destroy
    @place.destroy
    redirect_to places_url, :flash => { :success => 'Place was successfully deleted.' }
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place
      @place = Place.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def place_params
      params.require(:place).permit(:title)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def menu_item(name, icon = nil, options = nil, html_options = nil, &block)
    html_options ||= {}

    html_options[:class] ||= ""
    html_options[:class] += " nav-link"

    if icon.present?
      name = fa_icon icon, :text => name
    end

    active_link_to(name, options, html_options, &block)
  end

  def active_link_to(name = nil, options = nil, html_options = nil, &block)
    html_options ||= {}

    html_options[:class] ||= ""

    html_options[:class] += " active" if current_page?(options)

    link_to(name, options, html_options, &block)
  end

end

app/helpers/containers_helper.rb
module ContainersHelper
end

app/helpers/device_brands_helper.rb
module DeviceBrandsHelper
end

app/helpers/device_models_helper.rb
module DeviceModelsHelper
end

app/helpers/device_types_helper.rb
module DeviceTypesHelper
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/stock_items_helper.rb
module StockItemsHelper
end

app/views/items/_form.html.erb
<%= semantic_form_for @item do |f| %>
<%= f.inputs do %>
  <%= f.input :number %>
  <%= f.input :title %>
  <%= f.input :brand_name %>
  <%= f.input :model_description %>
  <%= f.input :serial_number %>
  <%= f.input :warranty_date %>
  <%= f.input :value %>
  <%= f.input :net_value %>
  <%= f.input :allocation %>
<% end %>

<%= f.actions do %>
<%= f.action :submit, :as => :input %>
<% end %>
<% end %>

app/views/items/edit.html.erb
<div class="page-header">
  <h1><%= Item.model_name.human  %></h1>
</div>

<ul class="nav nav-tabs justify-content-end">
  <li class="nav-item">
    <%= link_to (fa_icon 'list', :text => t_title(:index)), items_path, :class => 'nav-link' %>
  </li>
  <li class="nav-item">
    <%= link_to (fa_icon 'eye', :text => t_title(:show)), item_path(@item), :class => 'nav-link ' %>
  </li>
  <li class="nav-item">
    <%= link_to (fa_icon 'edit', :text => t_title(:edit)), edit_item_path(@item), :class => 'nav-link active ' %>
  </li>
  <li class="nav-item">
    <%= link_to (fa_icon 'trash', :text => t_title(:delete)), item_path(@item), :class => 'nav-link ', method: :delete, data: { confirm: t_confirm_delete(@item) } %>
  </li>
  <li class="nav-item">
    <%= link_to (fa_icon 'plus', :text => t_title(:new)), new_item_path, :class => 'nav-link' %>
  </li>
</ul>

<%= render 'form' %>

app/views/items/index.html.erb
<div class="page-header">
  <h1><%= Item.model_name.human  %></h1>
</div>

<div class="table-responsive">

  <ul class="nav nav-tabs justify-content-end" id="actions-tab">

    <li class="nav-item">
      <%= link_to (fa_icon 'list', :text => t_title(:index)), items_path, :class => "nav-link #{'active' if(!params[:q].present?)}" %>
    </li>

    <li class="nav-item">
      <a href="#search-bar" class="nav-link search-tab <%= 'active' if params[:q].present? %>" data-toggle="tab"><%= fa_icon 'search' %> <%= t_action :search %> </a>
    </li>
    <li class="nav-item">
      <%= link_to (fa_icon 'plus', :text => t_title(:new) ), new_item_path, :class => 'nav-link' %>
    </li>
  </ul>

  <%= render '/common/searchbar' %>

  <table class="table table-striped table-hover table-sm table-list ">
    <thead>
      <tr>
        <th><%= t_attr(:number) %></th>
        <th><%= t_attr(:title) %></th>
        <th><%= t_attr(:brand_name) %></th>
        <th><%= t_attr(:model_description) %></th>
        <th><%= t_attr(:serial_number) %></th>
        <th><%= t_attr(:warranty_date) %></th>
        <th><%= t_attr(:value) %></th>
        <th><%= t_attr(:net_value) %></th>
        <th><%= t_attr(:allocation) %></th>
        <th class="action"></th>
        <th class="action"></th>
        <th class="action"></th>
      </tr>
    </thead>

    <tbody>
      <% @items.each do |item| %>
       <tr>
          <td><%= item.number %></td>
          <td><%= item.title %></td>
          <td><%= item.brand_name %></td>
          <td><%= item.model_description %></td>
          <td><%= item.serial_number %></td>
          <td><%= l item.warranty_date, format: :short if item.warranty_date.present? %></td>
          <td><%= number_with_precision item.value, precision: 2 %></td>
          <td><%= number_with_precision item.net_value, precision: 2 %></td>
          <td><%= item.allocation %></td>

          <td class="action">
            <%= link_to item_path(item), :title => t_title(:show), :class => 'btn btn-sm btn-outline-info' do %><i class="far fa-eye"></i><% end %>
          </td>

          <td class="action">
            <%= link_to edit_item_path(item), :title => t_title(:edit), :class => 'btn btn-sm btn-outline-warning' do %>
              <i class="far fa-edit"></i>
            <% end %>
          </td>

          <td class="action">
            <%= link_to item_path(item), :title => t_title(:delete),  :class => 'btn btn-sm btn-outline-danger', method: :delete, data: { confirm: t_confirm_delete(item) } do %>
              <i class="far fa-trash-alt"></i>
            <% end %>
          </td>
        <% end %>
      </tr>
    </tbody>
  </table>
  <%= paginate(@items) %>
</div>

app/views/items/new.html.erb
<div class="page-header">
  <h1><%= Item.model_name.human  %></h1>
</div>


<ul class="nav nav-tabs justify-content-end">
  <li class="nav-item">
    <%= link_to (fa_icon 'list', :text => t_title(:index)), items_path, :class => 'nav-link' %>
  </li>
  <li class="nav-item">
    <%= link_to (fa_icon 'plus', :text => t_title(:new) ), new_item_path, :class => 'nav-link active' %>
  </li>
</ul>

<%= render 'form' %>

app/views/items/show.html.erb
<div class="page-header">
  <h1><%= Item.model_name.human  %></h1>
</div>

<div class="table-responsive">
  <ul class="nav nav-tabs justify-content-end">
    <li class="nav-item">
      <%= link_to (fa_icon 'list', :text => t_title(:index)), items_path, :class => 'nav-link' %>
    </li>
    <li class="nav-item">
      <%= link_to (fa_icon 'eye', :text => t_title(:show)), item_path(@item), :class => 'nav-link active' %>
    </li>
    <li class="nav-item">
      <%= link_to (fa_icon 'edit', :text => t_title(:edit)), edit_item_path(@item), :class => 'nav-link' %>
    </li>
    <li class="nav-item">
      <%= link_to (fa_icon 'trash', :text => t_title(:delete)), item_path(@item), :class => 'nav-link ', method: :delete, data: { confirm: t_confirm_delete(@item) } %>
    </li>
    <li class="nav-item">
      <%= link_to (fa_icon 'plus', :text => t_title(:new)), new_item_path, :class => 'nav-link' %>
    </li>
  </ul>
  <table class="table table-striped table-sm">
      <tr>
        <th><%= t_attr(:number) %></th>
        <td><%=  @item.number %></td>
      </tr>
      <tr>
        <th><%= t_attr(:title) %></th>
        <td><%=  @item.title %></td>
      </tr>
      <tr>
        <th><%= t_attr(:brand_name) %></th>
        <td><%=  @item.brand_name %></td>
      </tr>
      <tr>
        <th><%= t_attr(:model_description) %></th>
        <td><%=  @item.model_description %></td>
      </tr>
      <tr>
        <th><%= t_attr(:serial_number) %></th>
        <td><%=  @item.serial_number %></td>
      </tr>
      <tr>
        <th><%= t_attr(:warranty_date) %></th>
        <td><%=  l @item.warranty_date, format: :short if @item.warranty_date.present? %></td>
      </tr>
      <tr>
        <th><%= t_attr(:value) %></th>
        <td><%=  number_with_precision @item.value, precision: 2 %></td>
      </tr>
      <tr>
        <th><%= t_attr(:net_value) %></th>
        <td><%=  number_with_precision @item.net_value, precision: 2 %></td>
      </tr>
      <tr>
        <th><%= t_attr(:allocation) %></th>
        <td><%=  @item.allocation %></td>
      </tr>
  </table>
</div>

app/views/places/_form.html.erb
<%= semantic_form_for @place do |f| %>
<%= f.inputs do %>
  <%= f.input :title %>
<% end %>

<%= f.actions do %>
<%= f.action :submit, :as => :input %>
<% end %>
<% end %>

app/views/places/edit.html.erb
<div class="page-header">
  <h1><%= Place.model_name.human  %></h1>
</div>

<ul class="nav nav-tabs justify-content-end">
  <li class="nav-item">
    <%= link_to (fa_icon 'list', :text => t_title(:index)), places_path, :class => 'nav-link' %>
  </li>
  <li class="nav-item">
    <%= link_to (fa_icon 'eye', :text => t_title(:show)), place_path(@place), :class => 'nav-link ' %>
  </li>
  <li class="nav-item">
    <%= link_to (fa_icon 'edit', :text => t_title(:edit)), edit_place_path(@place), :class => 'nav-link active ' %>
  </li>
  <li class="nav-item">
    <%= link_to (fa_icon 'trash', :text => t_title(:delete)), place_path(@place), :class => 'nav-link ', method: :delete, data: { confirm: t_confirm_delete(@place) } %>
  </li>
  <li class="nav-item">
    <%= link_to (fa_icon 'plus', :text => t_title(:new)), new_place_path, :class => 'nav-link' %>
  </li>
</ul>

<%= render 'form' %>

app/views/places/index.html.erb
<div class="page-header">
  <h1><%= Place.model_name.human  %></h1>
</div>

<div class="table-responsive">
  <ul class="nav nav-tabs justify-content-end">
    <li class="nav-item">
      <%= link_to (fa_icon 'list', :text => t_title(:index)), places_path, :class => 'nav-link active' %>
    </li>
    <li class="nav-item">
      <%= link_to (fa_icon 'plus', :text => t_title(:new) ), new_place_path, :class => 'nav-link' %>
    </li>
  </ul>

  <table class="table table-striped table-hover table-sm">
    <thead>
      <tr>
        <th><%= t_attr(:title) %></th>
        <th class="action"></th>
        <th class="action"></th>
        <th class="action"></th>
      </tr>
    </thead>

    <tbody>
      <% @places.each do |place| %>
       <tr>
          <td><%= place.title %></td>

          <td class="action">
            <%= link_to place_path(place), :title => t_title(:show), :class => 'btn btn-sm btn-outline-info' do %><i class="far fa-eye"></i><% end %>
          </td>

          <td class="action">
            <%= link_to edit_place_path(place), :title => t_title(:edit), :class => 'btn btn-sm btn-outline-warning' do %>
              <i class="far fa-edit"></i>
            <% end %>
          </td>

          <td class="action">
            <%= link_to place_path(place), :title => t_title(:delete),  :class => 'btn btn-sm btn-outline-danger', method: :delete, data: { confirm: t_confirm_delete(place) } do %>
              <i class="far fa-trash-alt"></i>
            <% end %>
          </td>
        <% end %>
      </tr>
    </tbody>
  </table>
  <%= paginate(@places) %>
</div>

app/views/places/new.html.erb
<div class="page-header">
  <h1><%= Place.model_name.human  %></h1>
</div>


<ul class="nav nav-tabs justify-content-end">
  <li class="nav-item">
    <%= link_to (fa_icon 'list', :text => t_title(:index)), places_path, :class => 'nav-link' %>
  </li>
  <li class="nav-item">
    <%= link_to (fa_icon 'plus', :text => t_title(:new) ), new_place_path, :class => 'nav-link active' %>
  </li>
</ul>

<%= render 'form' %>

app/views/places/show.html.erb
<div class="page-header">
  <h1><%= Place.model_name.human  %></h1>
</div>

<div class="table-responsive">
  <ul class="nav nav-tabs justify-content-end">
    <li class="nav-item">
      <%= link_to (fa_icon 'list', :text => t_title(:index)), places_path, :class => 'nav-link' %>
    </li>
    <li class="nav-item">
      <%= link_to (fa_icon 'eye', :text => t_title(:show)), place_path(@place), :class => 'nav-link active' %>
    </li>
    <li class="nav-item">
      <%= link_to (fa_icon 'edit', :text => t_title(:edit)), edit_place_path(@place), :class => 'nav-link' %>
    </li>
    <li class="nav-item">
      <%= link_to (fa_icon 'trash', :text => t_title(:delete)), place_path(@place), :class => 'nav-link ', method: :delete, data: { confirm: t_confirm_delete(@place) } %>
    </li>
    <li class="nav-item">
      <%= link_to (fa_icon 'plus', :text => t_title(:new)), new_place_path, :class => 'nav-link' %>
    </li>
  </ul>
  <table class="table table-striped table-sm">
      <tr>
        <th><%= t_attr(:title) %></th>
        <td><%=  @place.title %></td>
      </tr>
  </table>
</div>