config/routes.rb
Rails.application.routes.draw do
  resources :containers
  resources :stock_items
  resources :device_types
  resources :device_brands
  resources :places
  resources :container_types
  resources :items
  resources :devices
  resources :device_models

  get '/', action: :index, controller: :pages
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  def self.search(query)
    if query.nil? || query.empty?
      return self.all
    end

    case self.verify_type query
    when :integer
      integers_fields = self.fields_by_type ActiveModel::Type::Integer

      where_str = "1=0 "
      integers_fields.each {|field| where_str += " OR #{field} = #{query}"}
      return self.where(where_str)
    when :text
      text_fields = self.fields_by_type ActiveModel::Type::String
      where_str = "1=0 "
      text_fields.each {|field| where_str += " OR #{field} LIKE \"%#{query}%\""}
      return self.where(where_str)
    end

  end

  private
    def self.fields_by_type (type)
      self.attribute_types.select {|attr, attrtype| attrtype.is_a?(type)}.keys;
    end

    def self.verify_type(str)
      return case str
        when /^([0-9]*)?$/ then :integer
        else :text
      end
    end

end

app/models/container.rb
class Container < ApplicationRecord
  belongs_to :place
  belongs_to :item
  belongs_to :container_type
  belongs_to :container
  def to_s
    self.title
  end
end

app/models/container_type.rb
class ContainerType < ApplicationRecord
end

app/models/device.rb
class Device < ApplicationRecord
  belongs_to :item
  belongs_to :device_model
  def to_s
    self.title
  end
end

app/models/device_brand.rb
class DeviceBrand < ApplicationRecord
  def to_s
    self.title
  end
end

app/models/device_model.rb
class DeviceModel < ApplicationRecord
  belongs_to :device_brand
  belongs_to :device_type
end

app/models/device_type.rb
class DeviceType < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord
  def to_s
    self.title
  end
end

app/models/place.rb
class Place < ApplicationRecord
end

app/models/stock_item.rb
class StockItem < ApplicationRecord
  belongs_to :item, required: false
  def to_s
    self.title
  end
end

app/controllers/container_types_controller.rb
class ContainerTypesController < ApplicationController
  before_action :set_container_type, only: [:show, :edit, :update, :destroy]

  # GET /container_types
  def index
    @container_types = ContainerType.all.order(sort_params).page(params[:page])
  end

  # GET /container_types/1
  def show
  end

  # GET /container_types/new
  def new
    @container_type = ContainerType.new
  end

  # GET /container_types/1/edit
  def edit
  end

  # POST /container_types
  def create
    @container_type = ContainerType.new(container_type_params)

    if @container_type.save
      redirect_to container_types_url, :flash => { :success => 'Container type was successfully created.' }
    else
      render :new
    end
  end

  # PATCH/PUT /container_types/1
  def update
    if @container_type.update(container_type_params)
      redirect_to container_types_url, :flash => { :success => 'Container type was successfully updated.' }
    else
      render :edit
    end
  end

  # DELETE /container_types/1
  def destroy
    @container_type.destroy
    redirect_to container_types_url, :flash => { :success => 'Container type was successfully deleted.' }
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_container_type
      @container_type = ContainerType.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def container_type_params
      params.require(:container_type).permit(:title, :slots, :nested)
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  def index
    @items = Item.all.search(search_params).order(sort_params).page(params[:page])
  end

  # GET /items/1
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  def create
    @item = Item.new(item_params)

    if @item.save
      redirect_to items_url, :flash => { :success => 'Item was successfully created.' }
    else
      render :new
    end
  end

  # PATCH/PUT /items/1
  def update
    if @item.update(item_params)
      redirect_to items_url, :flash => { :success => 'Item was successfully updated.' }
    else
      render :edit
    end
  end

  # DELETE /items/1
  def destroy
    @item.destroy
    redirect_to items_url, :flash => { :success => 'Item was successfully deleted.' }
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def item_params
      params.require(:item).permit(:number, :title, :brand_name, :model_description, :serial_number, :warranty_date, :value, :net_value, :allocation)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index

  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def menu_item(name, icon = nil, options = nil, html_options = nil, &block)
    html_options ||= {}

    html_options[:class] ||= ""
    html_options[:class] += " nav-link"

    if icon.present?
      name = fa_icon icon, :text => name
    end

    active_link_to(name, options, html_options, &block)
  end

  def active_link_to(name = nil, options = nil, html_options = nil, &block)
    html_options ||= {}

    html_options[:class] ||= ""

    html_options[:class] += " active" if current_page?(options)

    link_to(name, options, html_options, &block)
  end

end

app/helpers/container_types_helper.rb
module ContainerTypesHelper
end

app/helpers/containers_helper.rb
module ContainersHelper
end

app/helpers/device_brands_helper.rb
module DeviceBrandsHelper
end

app/helpers/device_types_helper.rb
module DeviceTypesHelper
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/stock_items_helper.rb
module StockItemsHelper
end

app/views/container_types/_form.html.erb
<%= semantic_form_for @container_type do |f| %>
<%= f.inputs do %>
  <%= f.input :title %>
  <%= f.input :slots %>
  <%= f.input :nested %>
<% end %>

<%= f.actions do %>
<%= f.action :submit, :as => :input %>
<% end %>
<% end %>

app/views/container_types/edit.html.erb
<div class="page-header">
  <h1>Container types</h1>
</div>

<ul class="nav nav-tabs justify-content-end">
  <li class="nav-item">
    <%= link_to (fa_icon 'list', :text => 'List'), container_types_path, :class => 'nav-link' %>
  </li>
  <li class="nav-item">
    <%= link_to (fa_icon 'eye', :text => 'Show Details'), container_type_path(@container_type), :class => 'nav-link ' %>
  </li>
  <li class="nav-item">
    <%= link_to (fa_icon 'edit', :text => 'Edit Container type'), edit_container_type_path(@container_type), :class => 'nav-link active ' %>
  </li>
  <li class="nav-item">
    <%= link_to (fa_icon 'trash', :text => 'Delete Container type'), container_type_path(@container_type), :class => 'nav-link ', method: :delete, data: { confirm: 'Are you sure?' } %>
  </li>
  <li class="nav-item">
    <%= link_to (fa_icon 'plus', :text => 'Add New Container type'), new_container_type_path, :class => 'nav-link' %>
  </li>
</ul>

<%= render 'form' %>

app/views/container_types/index.html.erb
<div class="page-header">
  <h1>Container types</h1>
</div>

<div class="table-responsive">
  <ul class="nav nav-tabs justify-content-end">
    <li class="nav-item">
      <%= link_to (fa_icon 'list', :text => 'List'), container_types_path, :class => 'nav-link active' %>
    </li>
    <li class="nav-item">
      <%= link_to (fa_icon 'plus', :text => 'Add New Container type'), new_container_type_path, :class => 'nav-link' %>
    </li>
  </ul>

  <table class="table table-striped table-hover table-sm">
    <thead>
      <tr>
            <th>Title</th>
            <th>Slots</th>
            <th>Nested</th>
            <th class="action"></th>
        <th class="action"></th>
        <th class="action"></th>
      </tr>
    </thead>

    <tbody>
      <% @container_types.each do |container_type| %>
        <%= content_tag :tr, id: dom_id(container_type), class: dom_class(container_type) do %>
                      <td><%= container_type.title %></td>
                      <td><%= container_type.slots %></td>
                      <td><%= container_type.nested %></td>
                    <td class="action"><%= link_to container_type_path(container_type), :class => 'btn btn-sm btn-outline-info' do %><i class="far fa-eye"></i><% end %></td>
          <td class="action">
            <%= link_to edit_container_type_path(container_type), :class => 'btn btn-sm btn-outline-warning' do %>
              <i class="far fa-edit"></i>
            <% end %>
          </td>
          <td class="action">
            <%= link_to container_type_path(container_type), :class => 'btn btn-sm btn-outline-danger', method: :delete, data: { confirm: 'Are you sure?' } do %>
              <i class="far fa-trash-alt"></i>
            <% end %>
          </td>
        <% end %>
      <% end %>
    </tbody>
  </table>
  <%= paginate(@container_types) %>
</div>

app/views/container_types/new.html.erb
<div class="page-header">
  <h1>Container types</h1>
</div>


<ul class="nav nav-tabs justify-content-end">
  <li class="nav-item">
    <%= link_to (fa_icon 'list', :text => 'List'), container_types_path, :class => 'nav-link ' %>
  </li>
  <li class="nav-item">
    <%= link_to (fa_icon 'plus', :text => 'Add New Container type'), new_container_type_path, :class => 'nav-link active' %>
  </li>
</ul>

<%= render 'form' %>

app/views/container_types/show.html.erb
<div class="page-header">
  <h1>Container types</h1>
</div>

<div class="table-responsive">
  <ul class="nav nav-tabs justify-content-end">
    <li class="nav-item">
      <%= link_to (fa_icon 'list', :text => 'List'), container_types_path, :class => 'nav-link' %>
    </li>
    <li class="nav-item">
      <%= link_to (fa_icon 'eye', :text => 'Show Details'), container_type_path(@container_type), :class => 'nav-link active' %>
    </li>
    <li class="nav-item">
      <%= link_to (fa_icon 'edit', :text => 'Edit Container type'), edit_container_type_path(@container_type), :class => 'nav-link ' %>
    </li>
    <li class="nav-item">
      <%= link_to (fa_icon 'trash', :text => 'Delete Container type'), container_type_path(@container_type), :class => 'nav-link ', method: :delete, data: { confirm: 'Are you sure?' } %>
    </li>
    <li class="nav-item">
      <%= link_to (fa_icon 'plus', :text => 'Add New Container type'), new_container_type_path, :class => 'nav-link' %>
    </li>
  </ul>
  <table class="table table-striped table-sm">
      <tr>
        <td>Title:</td>
        <td><%=  @container_type.title %></td>
      </tr>
      <tr>
        <td>Slots:</td>
        <td><%=  @container_type.slots %></td>
      </tr>
      <tr>
        <td>Nested:</td>
        <td><%=  @container_type.nested %></td>
      </tr>
  </table>
</div>