config/routes.rb
Rails.application.routes.draw do
  resources :containers
  resources :stock_items
  resources :device_types
  resources :device_brands
  resources :places
  resources :container_types
  resources :items
  resources :devices
  resources :device_models

  get '/', action: :index, controller: :pages
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  def self.search(query)
    if query.nil? || query.empty?
      return self.all
    end

    case self.verify_type query
    when :integer
      integers_fields = self.fields_by_type ActiveModel::Type::Integer

      where_str = "1=0 "
      integers_fields.each {|field| where_str += " OR #{field} = #{query}"}
      return self.where(where_str)
    when :text
      text_fields = self.fields_by_type ActiveModel::Type::String
      where_str = "1=0 "
      text_fields.each {|field| where_str += " OR #{field} LIKE \"%#{query}%\""}
      return self.where(where_str)
    end

  end

  private
    def self.fields_by_type (type)
      self.attribute_types.select {|attr, attrtype| attrtype.is_a?(type)}.keys;
    end

    def self.verify_type(str)
      return case str
        when /^([0-9]*)?$/ then :integer
        else :text
      end
    end

end

app/models/container.rb
class Container < ApplicationRecord
  belongs_to :place
  belongs_to :item
  belongs_to :container_type
  belongs_to :container
  def to_s
    self.title
  end
end

app/models/container_type.rb
class ContainerType < ApplicationRecord
end

app/models/device.rb
class Device < ApplicationRecord
  belongs_to :item
  belongs_to :device_model
  def to_s
    self.title
  end
end

app/models/device_brand.rb
class DeviceBrand < ApplicationRecord
  def to_s
    self.title
  end
end

app/models/device_model.rb
class DeviceModel < ApplicationRecord
  belongs_to :device_brand
  belongs_to :device_type
end

app/models/device_type.rb
class DeviceType < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord
  def to_s
    self.title
  end
end

app/models/place.rb
class Place < ApplicationRecord
end

app/models/stock_item.rb
class StockItem < ApplicationRecord
  belongs_to :item, required: false
  def to_s
    self.title
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  def index
    @items = Item.all.search(search_params).order(sort_params).page(params[:page])
  end

  # GET /items/1
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  def create
    @item = Item.new(item_params)

    if @item.save
      redirect_to items_url, :flash => { :success => 'Item was successfully created.' }
    else
      render :new
    end
  end

  # PATCH/PUT /items/1
  def update
    if @item.update(item_params)
      redirect_to items_url, :flash => { :success => 'Item was successfully updated.' }
    else
      render :edit
    end
  end

  # DELETE /items/1
  def destroy
    @item.destroy
    redirect_to items_url, :flash => { :success => 'Item was successfully deleted.' }
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def item_params
      params.require(:item).permit(:number, :title, :brand_name, :model_description, :serial_number, :warranty_date, :value, :net_value, :allocation)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index

  end

end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :set_place, only: [:show, :edit, :update, :destroy]

  # GET /places
  def index
    @places = Place.all.order(sort_params).page(params[:page])
  end

  # GET /places/1
  def show
  end

  # GET /places/new
  def new
    @place = Place.new
  end

  # GET /places/1/edit
  def edit
  end

  # POST /places
  def create
    @place = Place.new(place_params)

    if @place.save
      redirect_to places_url, :flash => { :success => 'Place was successfully created.' }
    else
      render :new
    end
  end

  # PATCH/PUT /places/1
  def update
    if @place.update(place_params)
      redirect_to places_url, :flash => { :success => 'Place was successfully updated.' }
    else
      render :edit
    end
  end

  # DELETE /places/1
  def destroy
    @place.destroy
    redirect_to places_url, :flash => { :success => 'Place was successfully deleted.' }
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place
      @place = Place.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def place_params
      params.require(:place).permit(:title)
    end
end

app/controllers/stock_items_controller.rb
class StockItemsController < ApplicationController
  before_action :set_stock_item, only: [:show, :edit, :update, :destroy]

  # GET /stock_items
  def index
    @stock_items = StockItem.all.search(search_params).order(sort_params).page(params[:page])
  end

  # GET /stock_items/1
  def show
  end

  # GET /stock_items/new
  def new
    @stock_item = StockItem.new
  end

  # GET /stock_items/1/edit
  def edit
  end

  # POST /stock_items
  def create
    @stock_item = StockItem.new(stock_item_params)

    if @stock_item.save
      redirect_to stock_items_url, redirect_notice(@stock_item)
    else
      render :new
    end
  end

  # PATCH/PUT /stock_items/1
  def update
    if @stock_item.update(stock_item_params)
      redirect_to stock_items_url, redirect_notice(@stock_item)
    else
      render :edit
    end
  end

  # DELETE /stock_items/1
  def destroy
    @stock_item.destroy
    redirect_to stock_items_url, redirect_notice(@stock_item)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stock_item
      @stock_item = StockItem.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def stock_item_params
      params.require(:stock_item).permit(:title, :item_id, :quantity, :is_package, :package_quantity)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def menu_item(name, icon = nil, options = nil, html_options = nil, &block)
    html_options ||= {}

    html_options[:class] ||= ""
    html_options[:class] += " nav-link"

    if icon.present?
      name = fa_icon icon, :text => name
    end

    active_link_to(name, options, html_options, &block)
  end

  def active_link_to(name = nil, options = nil, html_options = nil, &block)
    html_options ||= {}

    html_options[:class] ||= ""

    html_options[:class] += " active" if current_page?(options)

    link_to(name, options, html_options, &block)
  end

end

app/helpers/containers_helper.rb
module ContainersHelper
end

app/helpers/device_brands_helper.rb
module DeviceBrandsHelper
end

app/helpers/device_models_helper.rb
module DeviceModelsHelper
end

app/helpers/device_types_helper.rb
module DeviceTypesHelper
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/stock_items_helper.rb
module StockItemsHelper
end

app/views/stock_items/_form.html.erb
<%= semantic_form_for @stock_item do |f| %>
<%= f.inputs do %>
  <%= f.input :title %>
  <%= f.input :item, :prompt => t('.no-item') %>
  <%= f.input :quantity %>
  <%= f.input :is_package %>
  <%= f.input :package_quantity %>
<% end %>

<%= f.actions do %>
<%= f.action :submit, :as => :input %>
<% end %>
<% end %>

app/views/stock_items/edit.html.erb
<div class="page-header">
  <h1><%= StockItem.model_name.human  %></h1>
</div>

<ul class="nav nav-tabs justify-content-end">
  <li class="nav-item">
    <%= link_to (fa_icon 'list', :text => t_title(:index)), stock_items_path, :class => 'nav-link' %>
  </li>
  <li class="nav-item">
    <%= link_to (fa_icon 'eye', :text => t_title(:show)), stock_item_path(@stock_item), :class => 'nav-link ' %>
  </li>
  <li class="nav-item">
    <%= link_to (fa_icon 'edit', :text => t_title(:edit)), edit_stock_item_path(@stock_item), :class => 'nav-link active ' %>
  </li>
  <li class="nav-item">
    <%= link_to (fa_icon 'trash', :text => t_title(:delete)), stock_item_path(@stock_item), :class => 'nav-link ', method: :delete, data: { confirm: t_confirm_delete(@stock_item) } %>
  </li>
  <li class="nav-item">
    <%= link_to (fa_icon 'plus', :text => t_title(:new)), new_stock_item_path, :class => 'nav-link' %>
  </li>
</ul>

<%= render 'form' %>

app/views/stock_items/index.html.erb
<div class="page-header">
  <h1><%= StockItem.model_name.human  %></h1>
</div>

<div class="table-responsive">

  <ul class="nav nav-tabs justify-content-end" id="actions-tab">

    <li class="nav-item">
      <%= link_to (fa_icon 'list', :text => t_title(:index)), stock_items_path, :class => "nav-link #{'active' if(!params[:q].present?)}" %>
    </li>

    <li class="nav-item">
      <a href="#search-bar" class="nav-link search-tab <%= 'active' if params[:q].present? %>" data-toggle="tab"><%= fa_icon 'search' %> <%= t_action :search %> </a>
    </li>
    <li class="nav-item">
      <%= link_to (fa_icon 'plus', :text => t_title(:new) ), new_stock_item_path, :class => 'nav-link' %>
    </li>
  </ul>

  <%= render '/common/searchbar' %>

  <table class="table table-striped table-hover table-sm table-list ">
    <thead>
      <tr>
        <th><%= t_attr(:title) %></th>
        <th><%= t_attr(:item) %></th>
        <th><%= t_attr(:quantity) %></th>
        <th><%= t_attr(:is_package) %></th>
        <th><%= t_attr(:package_quantity) %></th>
        <th class="action"></th>
        <th class="action"></th>
        <th class="action"></th>
      </tr>
    </thead>

    <tbody>
      <% @stock_items.each do |stock_item| %>
       <tr>
          <td><%= stock_item.title %></td>
          <td><%= link_to_if stock_item.item, stock_item.item.try(:title), stock_item.item %></td>
          <td><%= stock_item.quantity %></td>
          <td><%= t stock_item.is_package %></td>
          <td><%= stock_item.package_quantity %></td>

          <td class="action">
            <%= link_to stock_item_path(stock_item), :title => t_title(:show), :class => 'btn btn-sm btn-outline-info' do %><i class="far fa-eye"></i><% end %>
          </td>

          <td class="action">
            <%= link_to edit_stock_item_path(stock_item), :title => t_title(:edit), :class => 'btn btn-sm btn-outline-warning' do %>
              <i class="far fa-edit"></i>
            <% end %>
          </td>

          <td class="action">
            <%= link_to stock_item_path(stock_item), :title => t_title(:delete),  :class => 'btn btn-sm btn-outline-danger', method: :delete, data: { confirm: t_confirm_delete(stock_item) } do %>
              <i class="far fa-trash-alt"></i>
            <% end %>
          </td>
        <% end %>
      </tr>
    </tbody>
  </table>
  <%= paginate(@stock_items) %>
</div>

app/views/stock_items/new.html.erb
<div class="page-header">
  <h1><%= StockItem.model_name.human  %></h1>
</div>


<ul class="nav nav-tabs justify-content-end">
  <li class="nav-item">
    <%= link_to (fa_icon 'list', :text => t_title(:index)), stock_items_path, :class => 'nav-link' %>
  </li>
  <li class="nav-item">
    <%= link_to (fa_icon 'plus', :text => t_title(:new) ), new_stock_item_path, :class => 'nav-link active' %>
  </li>
</ul>

<%= render 'form' %>

app/views/stock_items/show.html.erb
<div class="page-header">
  <h1><%= StockItem.model_name.human  %></h1>
</div>

<div class="table-responsive">
  <ul class="nav nav-tabs justify-content-end">
    <li class="nav-item">
      <%= link_to (fa_icon 'list', :text => t_title(:index)), stock_items_path, :class => 'nav-link' %>
    </li>
    <li class="nav-item">
      <%= link_to (fa_icon 'eye', :text => t_title(:show)), stock_item_path(@stock_item), :class => 'nav-link active' %>
    </li>
    <li class="nav-item">
      <%= link_to (fa_icon 'edit', :text => t_title(:edit)), edit_stock_item_path(@stock_item), :class => 'nav-link' %>
    </li>
    <li class="nav-item">
      <%= link_to (fa_icon 'trash', :text => t_title(:delete)), stock_item_path(@stock_item), :class => 'nav-link ', method: :delete, data: { confirm: t_confirm_delete(@stock_item) } %>
    </li>
    <li class="nav-item">
      <%= link_to (fa_icon 'plus', :text => t_title(:new)), new_stock_item_path, :class => 'nav-link' %>
    </li>
  </ul>
  <table class="table table-striped table-sm">
      <tr>
        <th><%= t_attr(:title) %></th>
        <td><%=  @stock_item.title %></td>
      </tr>
      <tr>
        <th><%= t_attr(:item) %></th>
        <td><%=  link_to_if @stock_item.item, @stock_item.item.try(:title), @stock_item.item %></td>
      </tr>
      <tr>
        <th><%= t_attr(:quantity) %></th>
        <td><%=  @stock_item.quantity %></td>
      </tr>
      <tr>
        <th><%= t_attr(:is_package) %></th>
        <td><%=  t @stock_item.is_package %></td>
      </tr>
      <tr>
        <th><%= t_attr(:package_quantity) %></th>
        <td><%=  @stock_item.package_quantity %></td>
      </tr>
  </table>
</div>